version: '2'

services:
  nodetemplate:
    build:
      context: ./
    image: ikakpalka:0.2
    command: python -m main
    environment:
      - IKAKPALKA_PORT=10000
    volumes:
      - ./src/:/app
  db:
    image: couchdb:1.6 
    container_name: local.ikp
    volumes:
      - ./db/data:/usr/local/var/lib/couchdb
    logging:
      options:
        max-size: "100m"
        max-file: "1"
  node1:
    extends:
      service: nodetemplate
    container_name: local.ikp.node1
  node2:
    extends:
      service: nodetemplate
    container_name: local.ikp.node2
  mailer:
    extends:
      service: nodetemplate
    container_name: local.ikp.mailer
    command: python -m mailer
  nginx:
    image: nginx:1.10
    container_name: local.ikp.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

networks:
  default:
    external:
      name: ikakpalka

